#!/bin/bash

# set output and error output
#SBATCH -o /home/vtinney/pubmed_batch/pubmed%j.out
#SBATCH -e /home/vtinney/pubmed_batch/pubmed%j.err

# default queue, single node
#SBATCH -p debug
#SBATCH -N 1
#SBATCH --mail-user=vtinney@gwu.edu
#SBATCH --mail-type=ALL

# time limit
#SBATCH -t 4:00:00

#SBATCH -D /home/vtinney/pubmed_batch/
#SBATCH -J pubmed

Link="http://www.ncbi.nlm.nih.gov/pubmed/"
PMCLink="http://www.ncbi.nlm.nih.gov/pmc/articles/"
ID=(30551059
30489348
30412999
30380717
30181279
29649153
)

for f in ${ID[@]};
do
  PMCID=$(wget  --user-agent="Mozilla/5.0 (Windows NT 5.2; rv:2.0.1) Gecko/20100101 Firefox/4.0.1" \
   -l1 --no-parent ${Link}${f} -O - 2>/dev/null | grep -Po 'PMC\d+' | head -n 1)
    if [ $PMCID ]; then
       wget  --user-agent="Mozilla/5.0 (Windows NT 5.2; rv:2.0.1) Gecko/20100101 Firefox/4.0.1" \
            -l1 --no-parent -A.pdf ${PMCLink}${PMCID}/pdf/ -O ${f}.pdf 2>/dev/null
    else
       echo "No PMC ID for $f"
    fi

done
